version: '2'
services:
  nginx:
    container_name: qgisserver-certifsuite-nginx
    image: nginx:1.13
    ports:
      - 8089:80
    networks:
      - qgis
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/metadata:/var/www/html/wms13/metadata
    depends_on:
      - qgis-master
  teamengine:
    container_name: qgisserver-certifsuite-teamengine
    image: qgisserver-certifsuite/teamengine-4
    volumes:
      - ./params.xml:/root/params.xml:ro
    ports:
      - 8081:8080
    networks:
      - qgis
    depends_on:
      - nginx
  qgis-master:
    container_name: qgisserver-certifsuite-master
    image: qgisserver-certifsuite/master
    networks:
      - qgis
    volumes:
      - ./data:/data

networks:
  qgis:
    driver: bridge
