- name: Copy ci shell script
  copy:
    dest: "/home/{{ user }}/certifsuite"
    src: ci.sh
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Update crontab to periodically run ogc tests
  cron:
    name: certifsuite ci
    user: "{{ user }}"
    minute: "0"
    hour: "6"
    job: >
      cd /home/{{ user }}/certifsuite/ && sh ci.sh > /tmp/certifsuite-ci.log 2>&1
