version: '2'
services:
  nginx:
    container_name: qgisserver-certifsuite-nginx
    image: nginx:1.13
    ports:
      - 8089:80
    networks:
      - qgis
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - qgis-master
  teamengine:
    container_name: ets-ogcapi-features10
    image: ogccite/ets-ogcapi-features10
    ports:
      - 8090:8080
    networks:
      - qgis
    depends_on:
      - nginx
  qgis-master:
    container_name: qgisserver-certifsuite-master
    image: qgisserver-certifsuite/master
    networks:
      - qgis
    volumes:
      - ./data:/data
    privileged: true

networks:
  qgis:
    driver: bridge
